
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { addHours, startOfDay, addDays, setHours, setMinutes } from "date-fns";

import { onboardingContent } from "@/lib/i18n/onboardingContent";
import { useDailyStore } from "@/lib/store/useDailyStore";
import { useTaskStore } from "@/lib/store/task-store";
import { useRoutineStore } from "@/lib/store/routine-store";
import { useCalendarStore } from "@/lib/store/calendar-store";

import Step1Goal from "./steps/Step1Goal";
// import StepTimeframe from "./steps/StepTimeframe";
// import StepConstraint from "./steps/StepConstraint";
// import StepDeepDive from "./steps/StepDeepDive";
// import StepPast from "./steps/StepPast";
// import StepStyle from "./steps/StepStyle";
// import StepVisualization from "./steps/StepVisualization";
// import StepReview from "./steps/StepReview";
import OnboardingLoading from "./OnboardingLoading";

// Define the data structure
export type OnboardingData = {
    goal: string;
    timeframe: string;
    constraint: string;
    deepDive: string;
    pastObstacle: string;
    workStyle: string;
    visualization: string;
};

const INITIAL_DATA: OnboardingData = {
    goal: "",
    timeframe: "90 days",
    constraint: "",
    deepDive: "",
    pastObstacle: "",
    workStyle: "",
    visualization: ""
};

export default function OnboardingFlow() {
    const router = useRouter();
    const { setInitialData } = useDailyStore();
    // No need to destructure other stores here, we use getState() for atomic updates during the async operation

    const [step, setStep] = useState(1);
    const [data, setData] = useState<OnboardingData>(INITIAL_DATA);
    const [isLoading, setIsLoading] = useState(false);

    // Simple language toggle for now (or context)
    const lang = "es"; // Force Spanish per user request
    const t = onboardingContent[lang];

    const nextStep = () => setStep(s => s + 1);
    const prevStep = () => setStep(s => Math.max(1, s - 1));

    const updateData = (key: keyof OnboardingData, value: string) => {
        setData(prev => ({ ...prev, [key]: value }));
    };

    const handleComplete = async () => {
        setIsLoading(true);
        try {
            // Updated Endpoint to use the /api/ one
            const res = await fetch('/api/onboarding', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ ...data, language: lang })
            });
            const plan = await res.json();

            console.log("Plan created:", plan);

            // --- 1. POPULATE TASKS (Backlog) ---
            const tasks = plan.executionBoard?.tasks || [];
            const taskStore = useTaskStore.getState();

            tasks.forEach((t: any) => {
                taskStore.addTask({
                    title: t.title,
                    priority: t.priority || 'important',
                    status: 'todo',
                    tags: [t.tag || 'onboarding'],
                    description: `Generated by Glow AI for goal: ${data.goal}`
                });
            });

            // --- 2. POPULATE DAILY VIEW (The "One Thing") ---
            if (tasks.length > 0) {
                const oneThing = {
                    id: tasks[0].id, // Reuse ID if possible
                    title: tasks[0].title,
                    duration: '90 min',
                    type: 'creative',
                    why: 'Highest leverage for your goal',
                    bestTime: 'Morning',
                    completed: false,
                    priority: 'one-thing'
                };

                const otherActions = tasks.slice(1).map((t: any) => ({
                    id: t.id,
                    title: t.title,
                    duration: '45 min',
                    type: 'admin',
                    why: 'Maintenance',
                    bestTime: 'Afternoon',
                    completed: false,
                    priority: 'secondary'
                }));

                // @ts-ignore
                setInitialData(oneThing, otherActions);
            }

            // --- 3. POPULATE ROUTINES (Habits) ---
            const routineStore = useRoutineStore.getState();
            if (plan.habits) {
                if (plan.habits.morning) {
                    const morningSteps = plan.habits.morning.map((h: any, i: number) => ({
                        id: `m-ai-${i}`,
                        title: h.title,
                        duration: h.duration || 10
                    }));

                    routineStore.updateRoutine('morning-1', {
                        steps: morningSteps,
                        description: `Optimized for: ${data.goal}`
                    });
                }

                if (plan.habits.evening) {
                    const eveningSteps = plan.habits.evening.map((h: any, i: number) => ({
                        id: `e-ai-${i}`,
                        title: h.title,
                        duration: h.duration || 10
                    }));

                    routineStore.updateRoutine('evening-1', {
                        steps: eveningSteps,
                        description: `Review and prep for: ${data.goal}`
                    });
                }
            }

            // --- 4. POPULATE CALENDAR ---
            const calendarStore = useCalendarStore.getState();
            if (plan.calendar?.blocks) {
                const today = startOfDay(new Date());
                plan.calendar.blocks.forEach((block: any) => {
                    // Parse "HH:MM"
                    const [startH, startM] = block.start.split(':').map(Number);
                    const [endH, endM] = block.end.split(':').map(Number);

                    calendarStore.addEvent({
                        userId: 'current-user', // value from auth
                        title: block.title,
                        startTime: setMinutes(setHours(today, startH), startM),
                        endTime: setMinutes(setHours(today, endH), endM),
                        timeZone: 'local',
                        type: block.type || 'DEEP_WORK_CREATIVE',
                        energyRequired: 'high',
                        status: 'scheduled',
                        isRecurring: true // Make them daily recurring by default for the "System"
                    });
                });
            }

            // Redirect to dashboard (daily view)
            router.push('/daily');
        } catch (error) {
            console.error("Error creating plan", error);
            setIsLoading(false);
        }
    };

    if (isLoading) {
        return <OnboardingLoading language={lang} />;
    }

    return (
        <div className="w-full max-w-2xl mx-auto">
            {/* Progress Bar */}
            <div className="mb-8 h-1 w-full bg-zinc-200 rounded-full overflow-hidden">
                <div
                    className="h-full bg-black dark:bg-white transition-all duration-500 ease-out"
                    style={{ width: `${(step / 8) * 100}%` }}
                />
            </div>

            <AnimatePresence mode="wait">
                <motion.div
                    key={step}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    transition={{ duration: 0.3 }}
                >
                    {/* Step Rendering Logic */}
                    {step === 1 && (
                        <Step1Goal
                            value={data.goal}
                            onChange={(v) => updateData('goal', v)}
                            onNext={nextStep}
                            content={t.step1}
                        />
                    )}

                    {/* Placeholder for other steps */}
                    {step > 1 && (
                        <div className="text-center p-10 bg-white dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-sm">
                            <p className="mb-4 text-zinc-500">Step {step} Coming Soon...</p>
                            <button onClick={handleComplete} className="bg-black text-white px-6 py-2 rounded-full font-medium hover:scale-105 transition-transform">
                                Dev Skip (Finish)
                            </button>
                        </div>
                    )}
                </motion.div>
            </AnimatePresence>
        </div>
    );
}
