"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { startOfDay, setHours, setMinutes } from "date-fns";

import { onboardingContent } from "@/lib/i18n/onboardingContent";
import { useDailyStore } from "@/lib/store/useDailyStore";
import { useTaskStore } from "@/lib/store/task-store";
import { useRoutineStore } from "@/lib/store/routine-store";
import { useCalendarStore } from "@/lib/store/calendar-store";
import { useOnboardingStore } from "@/lib/onboarding/store";
import { useLanguage } from "@/lib/i18n/LanguageContext";
import { useGoalStore } from "@/lib/store/goal-store";
import { saveBoard } from "@/lib/storage";

// Simple helper to guess area
const inferLifeArea = (goal: string): string => {
    const g = goal.toLowerCase();
    if (g.includes('dinero') || g.includes('ahorrar') || g.includes('invertir') || g.includes('income')) return 'area-1'; // Finances
    if (g.includes('salud') || g.includes('peso') || g.includes('correr') || g.includes('fit')) return 'area-2'; // Health
    if (g.includes('trabajo') || g.includes('negocio') || g.includes('career') || g.includes('cliente')) return 'area-3'; // Career
    return 'area-5'; // Default to Growth
};

import Step1Goal from "./steps/Step1Goal";
import { Step2Context } from "./steps/Step2Context";
import { Step3Past } from "./steps/Step3Past";
import { Step4Future } from "./steps/Step4Future";
import { Step5Reveal } from "./steps/Step5Reveal";
import OnboardingLoading from "./OnboardingLoading";

export default function OnboardingFlow() {
    const router = useRouter();
    const { setInitialData } = useDailyStore();
    const { language } = useLanguage();
    const t = onboardingContent[language];

    const {
        currentStep,
        answers,
        isLoading,
        setStep,
        nextStep: storeNextStep,
        setAnswer,
        setLoading
    } = useOnboardingStore();

    // Trigger AI generation when we reach step 5 (after future vision)
    useEffect(() => {
        if (currentStep === 5 && answers.futureSelfVision && !isLoading) {
            handleComplete();
        }
    }, [currentStep]);

    const handleStep1Next = () => {
        if (answers.goal) {
            storeNextStep();
        }
    };

    const handleComplete = async () => {
        setLoading(true);
        try {
            // Call the AI API with all collected data
            const res = await fetch('/api/onboarding', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    ...answers,
                    language
                })
            });

            if (!res.ok) {
                throw new Error(`API error: ${res.status}`);
            }

            const plan = await res.json();

            console.log("Plan created:", plan);

            // --- SAVE BOARD (Local Storage) ---
            saveBoard(plan);

            // --- 0. POPULATE GOALS (New Store) ---
            const goalStore = useGoalStore.getState();
            goalStore.addGoal({
                title: answers.goal,
                status: 'active',
                motivation: answers.motivation,
                // Simple heuristic to assign a life area based on keywords, or default to Growth
                lifeAreaId: inferLifeArea(answers.goal)
            });

            // --- 1. POPULATE TASKS (Backlog) ---
            const tasks = plan.executionBoard?.tasks || [];
            const taskStore = useTaskStore.getState();

            tasks.forEach((t: any) => {
                taskStore.addTask({
                    title: t.title,
                    priority: t.priority || 'important',
                    status: 'todo',
                    tags: [t.tag || 'onboarding'],
                    description: `Generated by Glow AI for goal: ${answers.goal}`
                });
            });

            // --- 2. POPULATE DAILY VIEW (The "One Thing") ---
            if (tasks.length > 0) {
                const oneThing = {
                    id: tasks[0].id || `task-${Date.now()}`,
                    title: tasks[0].title,
                    duration: '90 min',
                    type: 'creative',
                    why: 'Highest leverage for your goal',
                    bestTime: 'Morning',
                    completed: false,
                    priority: 'one-thing'
                };

                const otherActions = tasks.slice(1, 5).map((t: any, idx: number) => ({
                    id: t.id || `task-${Date.now()}-${idx}`,
                    title: t.title,
                    duration: '45 min',
                    type: 'admin',
                    why: 'Supporting action',
                    bestTime: 'Afternoon',
                    completed: false,
                    priority: 'secondary'
                }));

                setInitialData(oneThing, otherActions);
            }

            // --- 3. POPULATE ROUTINES (Habits) ---
            const routineStore = useRoutineStore.getState();
            if (plan.habits) {
                if (plan.habits.morning) {
                    const morningSteps = plan.habits.morning.map((h: any, i: number) => ({
                        id: `m-ai-${i}`,
                        title: typeof h === 'string' ? h : h.title,
                        duration: (typeof h === 'object' && h.duration) ? h.duration : 10
                    }));

                    routineStore.updateRoutine('morning-1', {
                        steps: morningSteps,
                        description: `Optimized for: ${answers.goal}`
                    });
                }

                if (plan.habits.evening) {
                    const eveningSteps = plan.habits.evening.map((h: any, i: number) => ({
                        id: `e-ai-${i}`,
                        title: typeof h === 'string' ? h : h.title,
                        duration: (typeof h === 'object' && h.duration) ? h.duration : 10
                    }));

                    routineStore.updateRoutine('evening-1', {
                        steps: eveningSteps,
                        description: `Review and prep for: ${answers.goal}`
                    });
                }
            }

            // --- 4. POPULATE CALENDAR ---
            const calendarStore = useCalendarStore.getState();
            if (plan.calendar?.blocks) {
                const today = startOfDay(new Date());
                plan.calendar.blocks.forEach((block: any) => {
                    // Parse "HH:MM"
                    const [startH, startM] = block.start.split(':').map(Number);
                    const [endH, endM] = block.end.split(':').map(Number);

                    calendarStore.addEvent({
                        userId: 'current-user',
                        title: block.title,
                        startTime: setMinutes(setHours(today, startH), startM),
                        endTime: setMinutes(setHours(today, endH), endM),
                        timeZone: 'local',
                        type: block.type || 'DEEP_WORK_CREATIVE',
                        energyRequired: 'high',
                        status: 'scheduled',
                        isRecurring: true
                    });
                });
            }

            // Move to reveal step
            storeNextStep();
            setLoading(false);
        } catch (error) {
            console.error("Error creating plan", error);
            setLoading(false);
            // Show error to user
            alert("Hubo un error al generar tu plan. Por favor intenta de nuevo.");
        }
    };

    if (isLoading) {
        return <OnboardingLoading language={language} />;
    }

    // If we're on step 6 (after generation), show reveal
    if (currentStep === 6) {
        return <Step5Reveal />;
    }

    return (
        <div className="w-full max-w-2xl mx-auto">
            {/* Progress Bar */}
            <div className="mb-8 h-1 w-full bg-zinc-200 dark:bg-zinc-800 rounded-full overflow-hidden">
                <div
                    className="h-full bg-gradient-to-r from-primary to-primary/60 transition-all duration-500 ease-out"
                    style={{ width: `${(currentStep / 5) * 100}%` }}
                />
            </div>

            <AnimatePresence mode="wait">
                <motion.div
                    key={currentStep}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    transition={{ duration: 0.3 }}
                >
                    {currentStep === 1 && (
                        <Step1Goal
                            value={answers.goal}
                            onChange={(v) => setAnswer('goal', v)}
                            onNext={handleStep1Next}
                            content={t.step1}
                        />
                    )}

                    {currentStep === 2 && <Step2Context />}

                    {currentStep === 3 && <Step3Past />}

                    {currentStep === 4 && <Step4Future />}
                </motion.div>
            </AnimatePresence>

            {/* Dev Skip Button (only in development) */}
            {process.env.NODE_ENV === 'development' && currentStep < 4 && (
                <div className="mt-8 text-center">
                    <button
                        onClick={() => {
                            // Fill minimal data and skip to generation
                            if (!answers.goal) setAnswer('goal', 'Mejorar mi salud y productividad');
                            if (!answers.constraint) setAnswer('constraint', 'Time');
                            if (answers.obstacles.length === 0) setAnswer('obstacles', ['Falta de motivación']);
                            if (!answers.futureSelfVision) setAnswer('futureSelfVision', 'Me siento energizado y productivo cada día');
                            setStep(5);
                        }}
                        className="text-xs text-zinc-400 hover:text-zinc-600 dark:text-zinc-600 dark:hover:text-zinc-400"
                    >
                        Dev Skip →
                    </button>
                </div>
            )}
        </div>
    );
}
